### ISSUE TITLE
Semantic release bot changes our Gemfile.lock

### ISSUE THREAD

**Issue by geshwho** [Gusto/apollo-federation-ruby#169] opened 2022-01-29 00:51 UTC
The specific problematic bit is that it adds `-x86_64-linux` to the google-protobuf gem. [Here](https://github.com/Gusto/apollo-federation-ruby/commit/f24e83ed569770b96ed0ffd6a4b1f80f6203147b#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR45) is an example commit.

**Comment by daemonsy** [comment] 2022-01-31 20:06
## Reproduction
I spent some time investigating this and made some progress in reproducing this issue. 

We have an option in semantic release rubygems that installs and update lockfiles of the appraisal to the latest version of the gem after release. That's pretty neat, it means all the specs are declared to run on the latest version. 

In the [config](https://github.com/Gusto/apollo-federation-ruby/blob/f24e83ed569770b96ed0ffd6a4b1f80f6203147b/release.config.js#L9), we have an option `updateGemfileLock` that runs `bundle exec appraisal install`. Just for context, after this, the files are committed by semantic release bot using the git plugin. 

This in terms generates statements like: 

```
bundle check --gemfile='/Users/damon.aw/code/apollo-federation-ruby/gemfiles/graphql_1.10.gemfile' || bundle install --gemfile='/Users/damon.aw/code/apollo-federation-ruby/gemfiles/graphql_1.10.gemfile' --retry 1
bundle check --gemfile='/Users/damon.aw/code/apollo-federation-ruby/gemfiles/graphql_1.11.gemfile' || bundle install --gemfile='/Users/damon.aw/code/apollo-federation-ruby/gemfiles/graphql_1.11.gemfile' --retry 1
bundle check --gemfile='/Users/damon.aw/code/apollo-federation-ruby/gemfiles/graphql_1.12.gemfile' || bundle install --gemfile='/Users/damon.aw/code/apollo-federation-ruby/gemfiles/graphql_1.12.gemfile' --retry 1
```

Running this locally by bumping the gem version, I realized the `bundle check` command seems to change our `Gemfile.lock` in the main repo. 

I've confirmed that adding `--dry-run` option stops the bundle check from changing the lockfiles. 

## Next steps 

1. File an issue to Rubygems

2. We could just run `bundle exec appraisal install` to avoid calling bundle check for now.

**Comment by daemonsy** [comment] 2022-01-31 21:55
https://github.com/rubygems/rubygems/issues/5325

**Comment by grxy** [comment] 2023-03-08 17:52
Closing this since I believe it was fixed at some point when the bundler version was upgraded.

**Closed by grxy** 2023-03-08 17:52 UTC
